version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - .:/postgresql/data
    container_name: teachbase_db
    env_file:
      - ./.env
    ports:
      - 5432:5432

  web:
    build: .
    volumes:
      - .:/web/data
    container_name: teachbase_app
    command: bash entrypoint.sh
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
