# Generated by Django 4.1.7 on 2023-03-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_id", models.IntegerField()),
                ("content_type", models.PositiveSmallIntegerField()),
                ("owner_name", models.CharField(max_length=255)),
                ("thumb_url", models.URLField(blank=True, null=True)),
                ("cover_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField()),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("total_score", models.IntegerField()),
                ("total_tasks", models.IntegerField()),
                ("is_netology", models.BooleanField()),
                ("bg_url", models.URLField(blank=True, null=True)),
                ("video_url", models.URLField(blank=True, null=True)),
                ("demo", models.BooleanField()),
                ("unchangeable", models.BooleanField()),
                ("include_weekly_report", models.BooleanField()),
                ("custom_author_names", models.CharField(max_length=255)),
                ("custom_contents_link", models.URLField(blank=True, null=True)),
                ("hide_viewer_navigation", models.BooleanField()),
                ("duration", models.TimeField(blank=True, null=True)),
                ("account_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                ("phone", models.CharField(max_length=11)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("lang", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("role_id", models.IntegerField(blank=True, null=True)),
                ("auth_type", models.IntegerField(blank=True, null=True)),
                ("labels", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
